ServerEvents.recipes(e=>{
    e.shapeless(
        "mekanism:creative_chemical_tank",
        "mekanism:creative_chemical_tank"
    )
    e.shapeless(
        "mekanism:creative_fluid_tank",
        "mekanism:creative_fluid_tank"
    )
    e.shapeless(
        "mekanism:creative_energy_cube",
        "mekanism:creative_energy_cube"
    )
})