
#CompactFissionReactor Settings
[compactfissionreactor]
	#The capacity in mB of the waste tank of fuel in the Compact Fission Reactor
	#Range: 1 ~ 9223372036854775807
	tankCapacity = 18000000
	#The capacity in mB of the gas coolant tank of fuel in the Compact Fission Reactor
	#Range: 1 ~ 9223372036854775807
	GascoolanttankCapacity = 18000000000
	#The capacity in mB of the fluid coolant tank of fuel in the Compact Fission Reactor
	#Range: > 1
	FluidcoolanttankCapacity = 2147483647
	#The capacity in mB of the heated coolant tank of fuel in the Compact Fission Reactor
	#Range: 1 ~ 9223372036854775807
	HeatedcoolanttankCapacity = 18000000000
	#Max fuel cosume per tick of Compact Fission Reactor
	#Range: 1 ~ 9223372036854775807
	burnrate = 1920
	#Energy Capacity of Compact Fission Reactor
	#Range: 1 ~ 9223372036854775807
	energycapacity = 2500000000
	#The heat capacity of Compact Fission Reactor
	#Range: 1.0 ~ 1.7976931348623157E308
	HeatCapacity = 1000000.0

#CompactFissionReactor Settings
[compactturbine]
	#Gas Tank Capacity  of Compact Industrial Turbine
	#maxoutput
	#Range: 1 ~ 9223372036854775807
	maxoutput = 2000000000000
	#Energy Capacity of Compact Industrial Turbine
	#Range: 0 ~ 9223372036854775807
	gastankcapacity = 2000000000000
	#Fluid Tank Capacity of Compact Industrial Turbine
	#Range: > 0
	fluidtankcapacity = 2147483647
	#turbine energy production rate magnification
	#Range: 0.0 ~ 1.7976931348623157E308
	energymagnification = 2.56E7
	#amount of virtual turbine condenser block
	#Range: > 0
	virtualcondenser = 500
	#amount of virtual turbine disperser block
	#Range: > 0
	virtualvent = 500
	#amount of virtual turbine vent block
	#Range: > 0
	upvolume = 800
	#amount of virtual blade
	#Range: > 0
	blades = 200
	#vertual volume of lower section
	#Range: > 0
	lowervolume = 500

