
#MS Energy Usage Config. This config is synced from server to client.
[storage]
	#Energy per operation tick (Joules).
	adsorptionTypeSeawaterMetalExtractor = "100"
	#Energy per operation tick (Joules).
	organicLiquidExtractor = "100"
	#Energy per operation tick (Joules).
	seawaterPump = "100"

