//priority: 999
/**
 * 
 */
global.MaterialList=[
    {
        name:"cosmic",
        hardness:5,
        color:11032575,
        hasRod:true,
        hasFrame:true,
        hasIngot:true,
    },
    {
        name:"test",
        hardness:5,
        color:0xc15a36,
        hasRod:true,
        hasFrame:true,
        hasIngot:true,
    },
]