ServerEvents.recipes(e=>{
    if(isHardMode){
        e.remove({output:"compactmekanismmachines:compact_fission_reactor"})
        e.remove({output:"compactmekanismmachines:compact_industrial_turbine"})
        e.recipes.extendedcrafting.shaped_table(
          "compactmekanismmachines:compact_fission_reactor",
          [
            "ABBBCCCBBBA",
            "BDDDDDDDDDB",
            "BEEFFGFFEEB",
            "BEHHHIHHHEB",
            "CFHHHIHHHFC",
            "CGHHHIHHHGC",
            "CFHHHIHHHFC",
            "BEHHHIHHHEB",
            "BEEFFGFFEEB",
            "BDDDDDDDDDB",
            "ABBBCCCBBBA"
          ],
          {
            A:'mekanism_extras:infinite_control_circuit',
            B:'mekanismgenerators:fission_reactor_casing',
            C:'mekanismgenerators:fission_reactor_port',
            D:'mekanismgenerators:fission_reactor_logic_adapter',
            E:'techreborn:iridium_alloy_ingot',
            F:'mekanismgenerators:control_rod_assembly',
            G:'mekanism_extras:naquadah_reactor_casing',
            H:'mekanismgenerators:fission_fuel_assembly',
            I:'mekanism_extras:expand_radioactive_waste_barrel'
          }
        )
        e.recipes.extendedcrafting.shaped_table(
          "compactmekanismmachines:compact_industrial_turbine",
          [
            "ABBBCCCBBBA",
            "BDDDDDDDDDB",
            "BEEFFGFFEEB",
            "BEHHHIHHHEB",
            "CFHHHIHHHFC",
            "CGHHHIHHHGC",
            "CFHHHIHHHFC",
            "BEHHHIHHHEB",
            "BEEFFGFFEEB",
            "BDDDDDDDDDB",
            "ABBBCCCBBBA"
          ],
          {
            A:'mekanism_extras:infinite_control_circuit',
            B:'mekanismgenerators:turbine_casing',
            C:'mekanismgenerators:turbine_vent',
            D:'mekanismgenerators:electromagnetic_coil',
            E:'mekanismgenerators:turbine_blade',
            F:'mekanism:ultimate_energy_cube',
            G:'mekanismgenerators:rotational_complex',
            H:'mekanismgenerators:saturating_condenser',
            I:'mekanismgenerators:turbine_rotor'
          }
        )
    }
    if(isNormalMode){
        e.remove({output:"compactmekanismmachines:compact_fission_reactor"})
        e.remove({output:"compactmekanismmachines:compact_industrial_turbine"})
        e.recipes.extendedcrafting.shaped_table(
            "compactmekanismmachines:compact_fission_reactor",
            [
              "AAAAAAAAA",
              "ABCBCBCBA",
              "ACDEEEDCA",
              "ABEFFFEBA",
              "ACEFGFECA",
              "ABEFFFEBA",
              "ACDEEEDCA",
              "ABCBCBCBA",
              "AAAAAAAAA"
            ],
            {
              A:{item:"mekanismgenerators:fission_reactor_casing"},
              B:{item:"mekanismgenerators:fission_fuel_assembly"},
              C:{item:"mekanismgenerators:control_rod_assembly"},
              D:{item:"mekanism_extras:infinite_chemical_tank"},
              E:{item:"mekanism_extras:infinite_control_circuit"},
              F:{item:"mekanism_extras:alloy_spectrum"},
              G:{item:"mekanism_extras:expand_radioactive_waste_barrel"}
            }
          )
        e.recipes.extendedcrafting.shaped_table(
          "compactmekanismmachines:compact_industrial_turbine",
          [
            "AAAAAAA",
            "ABCDCBA",
            "AEFGFEA",
            "AHFGFHA",
            "AIFGFIA",
            "AJFGFJA",
            "AAAAAAA"
          ],
          {
            A:{item:'mekanismgenerators:turbine_casing'},
            B:{item:'mekanism_extras:alloy_radiance'},
            C:{item:'mekanismscience:pellet_neutron_source'},
            D:{item:'mekanismgenerators:electromagnetic_coil'},
            E:{item:'mekanism:pressure_disperser'},
            F:{item:'mekanismgenerators:turbine_blade'},
            G:{item:'mekanismgenerators:turbine_rotor'},
            H:{item:'mekanismgenerators:saturating_condenser'},
            I:{item:"mekanismgenerators:turbine_vent"},
            J:{item:'mekanism_extras:absolute_control_circuit'}
          }
        )
    }
})