
[General]
	#Energy usage for machine with no upgrades [default:1024]
	#Range: 1 ~ 1048576
	"Base Machine Energy Usage" = 1024
	#Initial time in ticks for a void pump/miner [default:126]
	#Range: 1 ~ 2000
	"Machine Max Generation Time" = 126
	#Value to scale energy usage by with energy upgrades [default:1.3]
	#Range: 0.0010000000474974513 ~ 4.0
	"Machine Energy Usage Energy Upgrade Scale" = 1.2999999523162842
	#Value to scale energy usage by with speed upgrades [default:2]
	#Range: 0.0010000000474974513 ~ 8.0
	"Machine Energy Usage Speed Upgrade Scale" = 2.0
	#Value to scale collection speed with speed upgrades (in ticks) [default:5]
	#Range: 0.0010000000474974513 ~ 8.0
	"Machine Speed Upgrade Scale" = 5.0
	#Maximum number of energy upgrades [default:24]
	#Range: 0 ~ 256
	"Max Energy Upgrades" = 24
	#Maximum number of speed upgrades [default:24]
	#Range: 0 ~ 256
	"Max Speed Upgrades" = 24
	#Chunkloader radius in Chunks [default:1]
	#Range: 0 ~ 1
	"Chunkloader Radius" = 1

["Void Miner"]
	#To get an items tag / item id, use /cvm iteminfo while holding an item
	#Void Miner Partial Tag Blacklist (case insensitive)
	"Partial Tag Blacklist" = []
	#Void Miner Exact Tag Blacklist (case sensitive)
	"Exact Tag Blacklist" = []
	#Void Miner Item ID Blacklist (case insensitive) e.g. minecraft:stone
	"Item Blacklist" = []
	#Void Miner Wildcard Item ID Blacklist (Wildcard: *) (case insensitive) e.g. mekanism:*
	"Wildcard Item Blacklist" = []
	#Void Miner Enabled Tag Filters/Prefixes (case sensitive)
	#Valid prefixes: storage_block,seed,plastic,plate,dye,gem,nugget,ore,ingot,glass,misc,rod,logs,crop,dust,stone
	"Enabled Filters/Prefixes" = ["storage_block", "seed", "plastic", "plate", "dye", "gem", "nugget", "ore", "ingot", "glass", "misc", "rod", "logs", "crop", "dust", "stone"]

["Void Pump"]
	#Void Pump Partial Fluid Blacklist (prefix fluid. not required) (case insensitive)
	"Partial Fluid Blacklist" = []
	#Void Pump Exact Fluid Blacklist (prefix fluid. not required) (case sensitive)
	"Exact Fluid Blacklist" = []

