#Whether to allow enchanting of Meka-Tool
mekaToolEnchantable = true
#Enchantability of Meka-Tool. Higher values mean better enchantments
#Range: > 1
mekaToolEnchantability = 15
#Whether to allow ALL enchantments on Meka-Tool. Set false to limit to tools and weapons enchantments
mekaToolAllowAllEnchantments = true
#Whether to allow enchanting of Atomic Disassembler
atomicDisassemblerEnchantable = true
#Enchantability of Atomic Disassembler. Higher values mean better enchantments
#Range: > 1
atomicDisassemblerEnchantability = 15
#Whether to allow ALL enchantments on Atomic Disassembler. Set false to limit to tools and weapons enchantments
atomicDisassemblerAllowAllEnchantments = true
#Whether to allow enchanting of Electric Bow in Enchanting Table
electricBowEnchantable = true
#Enchantability of Electric Bow. Higher values mean better enchantments
#Range: > 1
electricBowEnchantability = 15
#Whether to allow enchanting of armors, such as Meka-Suit, (Armored) Jetpack, (Armored) Free Runners, etc.
armorEnchantable = true
#Enchantability of armors. Higher values mean better enchantments
#Range: > 1
armorEnchantability = 15

